//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public long id { get; set; }
        public Nullable<int> id_tipo { get; set; }
        public string Code { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Id_tipo_code_standar { get; set; }
        public Nullable<int> Id_unidad_medida { get; set; }
        public double Precio_unitario { get; set; }
        public Nullable<int> id_tipo_impuesto { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public Nullable<int> Cantidad_por_paquete { get; set; }
        public int Cantidad_real { get; set; }
        public Nullable<int> id_mandato { get; set; }
        public Nullable<int> id_transporte_carga { get; set; }
        public Nullable<int> id_precio_pais { get; set; }
        public string Comentarios { get; set; }
        public System.DateTime Created_at { get; set; }
        public System.DateTime Updated_at { get; set; }
        public bool Is_active { get; set; }
        public Nullable<System.DateTime> Expiration_date { get; set; }
        public Nullable<double> Max_stock { get; set; }
        public string ubicacion { get; set; }
        public Nullable<long> inventary { get; set; }
    
        public virtual Mandatos Mandatos { get; set; }
        public virtual PreciosPorPais PreciosPorPais { get; set; }
        public virtual TiposProducto TiposProducto { get; set; }
        public virtual TipoCodStandar TipoCodStandar { get; set; }
        public virtual TipoImpuesto TipoImpuesto { get; set; }
        public virtual TipoTransCarga TipoTransCarga { get; set; }
        public virtual UnidadesUM UnidadesUM { get; set; }
    }
}
